### ISSUE TITLE
Temperature reporting with two decimals

### ISSUE THREAD

**Issue by chheiss** [briis/smartweatherudp#39]
Hi! Since the last update, the tempest temperature is reporting with two decimals, like 3.51

A template sensor to round that does not work. Can you fix that?

**Comment by natekspencer** [comment]
I'll work on rounding it, but templates should still work with it:

```yaml
template:
  - sensor:
    - name: "Tempest Temp"
      unit_of_measurement: "°F"
      state: >
        {{ states("sensor.tempest_temperature") | round(1) }}
```

Or am I misunderstanding?
